# -*- coding: utf-8 -*-
"""Basic_EDA.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fvGhVIhpsBvjZ51U5QpAMiDQxmebN3li
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
import numpy as np
import os
import matplotlib.pyplot as plt
import seaborn as sns
# %matplotlib inline




# %matplotlib inline
sns.set()

df = pd.read_csv("FinalTestData_1.csv")
df

df.shape

df.info

df.isna().sum()

df.describe()

df["Year"].value_counts()

df["Winner"].value_counts()

sns.pairplot(df,hue="Winner")

sns.countplot(x='Winner', data=df);

sns.countplot(x='Score', data=df);

df.groupby('Winner').hist(alpha=0.6);

sns.stripplot(x='Winner', y='APPG', data=df, alpha=0.3, jitter=True);

sns.stripplot(x='Winner', y='WPT', data=df, alpha=0.3, jitter=True);

sns.lmplot(x='APPG', y='WPT', hue='Winner', data=df, fit_reg=False, scatter_kws={'alpha':0.5});

