# -*- coding: utf-8 -*-
"""Pre-Processing- FinalTestData.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BM9sG1NxOea93Zd4tNd5G-PNXPZIQHly
"""

import pandas as pd 
import csv
import random
# import and remove spaces and new line charachters 
df = pd.read_csv("Prem_scores_1.csv")
df = df.replace('\n','', regex=True) 
df = df.replace('\r','', regex=True) 
df1 = pd.read_csv('Prem_Stats_Yearly_1.csv')
df1 = df1.replace('\n','', regex=True) 
df1 = df1.replace('\r','', regex=True)

df = df[df.Draw != 1]

#set up columns for new file
output_file = csv.writer(open('FinalTestData.csv','w', newline = ''))
output_file.writerow(['Year','WP1','HWP','AWP','APPG1','WP2','HWP2','AWP2','APPG2','Score','Winner','WPT','HWPT','AWPT','APPG'])
                        
#import columns from prem_scores_1 & Prem_Stats_yearly_1
teamList1 = df['Home_Team'].values.tolist()
team1Score = df['HTScore'].values.tolist()
teamList2 = df['Away_Team'].values.tolist()
team2Score = df['ATScore'].values.tolist()
Year1 = df['Year'].values.tolist()
Year2 = df1['Year'].values.tolist()
teamsY = df1['Team'].values.tolist()
WP = df1['WinPercent'].values.tolist()
HWP = df1['Home_win_pc'].values.tolist()
AWP = df1['Away_win_pc'].values.tolist()
APPG = df1['average_points_per_game'].values.tolist()

#setting a list for both teams
team1 = []
team2 = []
#making sure there are no spaces 
for team in teamList1:
    team1.append(team.strip())
for team in teamList2:
    team2.append(team.strip())

# corrolating the year with the home and away team 
l = len(team1)
for i in range(l):
    year = Year1[i]
    t1 = team1[i]
    t1S = int(team1Score[i])
    t2 = team2[i]
    t2S = int(team2Score[i])
    foundT1 = False
    foundT2 = False

#setting the winner
    score = t1S - t2S
    if(score>0):
        winner = 0
    elif(score<0):
        winner = 1
    else:
        winner = -1
    k = 0 
    
#looking at the first team, adding average points per game, win %, home win %, away win %
    while(not foundT1):
        if(Year2[k]==year and teamsY[k]==t1):
            ap1 = APPG[k]
            wp1 = round(WP[k],0)
            hwp1 = round(HWP[k],3)
            awp1 = round(AWP[k],3)
            foundT1 = True
        k+=1
    k=0
    
#same for the other team
    while(not foundT2):
        if(Year2[k]==year and teamsY[k]==t2):
            ap2 = APPG[k]
            wp2 = round(WP[k],0)
            hwp2 = round(HWP[k],3)
            awp2 = round(AWP[k],3)
            foundT2 = True
        k+=1
#find total for all values
    wpt = wp1 - wp2
    hwpt = hwp1 - hwp2
    awpt = awp1 - awp2
    appgt = ap1 - ap2
# #put correct figures in correct columns
    if winner != -1:
        output_file.writerow([year,wp1,hwp1,awp1,ap1,wp2,hwp2,awp2,ap2,score,winner,wpt,round(hwpt,3),round(awpt,3),round(appgt,3)])